server:
  port: 8080
  context-path: /
localConstant:
  projectName: xbbDingtalkTest
jedis:
  pool:
    host: redis.server
    port: 6379
    timeout: 0
    password: mUWPMPpWyv8I069o
    config:
      maxTotal: 30
      maxIdle: 10
      maxWaitMillis: 1500